imports:
    - { resource: config_dev.yml }

parameters:
  database_name: product_api_test

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false
